CREATE DATABASE IF NOT EXISTS `game_shop` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `game_shop`;

SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `GAME` CASCADE;
DROP TABLE IF EXISTS `PUBLISHER` CASCADE;
DROP TABLE IF EXISTS `GENDER` CASCADE;
DROP TABLE IF EXISTS `DEVELOPER` CASCADE;
DROP TABLE IF EXISTS `PUBLISH` CASCADE;
DROP TABLE IF EXISTS `DEVELOP` CASCADE;
DROP TABLE IF EXISTS `GENDER_GAME` CASCADE;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE `GAME` (
    `id` INT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `publisher` VARCHAR(100) NOT NULL,
    `released_year` INT NOT NULL,
    `website` TEXT NOT NULL,
    `media_url` TEXT NOT NULL,
    `description` TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `GENDER`(
    `gender` VARCHAR(50) PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `DEVELOPER` (
    `name` VARCHAR(50) PRIMARY KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `DEVELOP` (
   `name` VARCHAR(50) NOT NULL,
   `id_game` INT NOT NULL,
   FOREIGN KEY (`name`) REFERENCES `DEVELOPER` (`name`) ON DELETE CASCADE,
   FOREIGN KEY (`id_game`) REFERENCES `GAME` (`id`) ON DELETE CASCADE,
   PRIMARY KEY (`name`, `id_game`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `GENDER_GAME` (
    `gender` VARCHAR(50) NOT NULL,
    `id_game` INT NOT NULL,
    FOREIGN KEY (`gender`) REFERENCES `GENDER` (`gender`) ON DELETE CASCADE,
    FOREIGN KEY (`id_game`) REFERENCES `GAME` (`id`) ON DELETE CASCADE,
    PRIMARY KEY (`gender`, `id_game`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;